# fly.toml app configuration file generated for dnd-tracker-next-js on 2025-07-01T00:20:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dnd-tracker-next-js'
primary_region = 'sea'

[build]

#[deploy]
#  release_command = "npm run migrate:up"

[env]
  NODE_ENV = "production"
  MIGRATION_TIMEOUT = "300000"
  MIGRATION_BACKUP_ENABLED = "true"
  MIGRATION_DRY_RUN = "false"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "get"
    path = "/api/health"
    timeout = "10s"
    restart_limit = 6

  [[http_service.checks]]
    grace_period = "60s"
    interval = "60s"
    method = "get"
    path = "/api/health/migrations"
    timeout = "15s"
    restart_limit = 3

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
