name: Codacy Coverage Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codacy-coverage-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:ci
        env:
          # Set mock MongoDB environment variables for CI
          MONGODB_URI: 'mongodb://localhost:27017'
          MONGODB_DB_NAME: 'test-db'
          # Add flag to indicate we're in CI environment
          CI: true
          NODE_ENV: 'test'

      - name: Run Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info
